language: python
python:
  - 2.7
  - 3.4

script:
  - python setup.py test

before_script:
  - pip install python-coveralls
  - psql -c 'create database dummy_db;' -U postgres
  - mv travis_config.py test_config.py
after_success:
  - coveralls