language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  script: python setup.py test

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database dummy_db;' -U postgres
  - mv travis_config.py test_config.py